class CLI
    
    def call
        Api.teams
        welcome
        list
        menu
    end


    def menu
        puts "Please select a team."
        input = nil
            while input!= "exit"
                input = gets.strip.downcase
                case input
                when "1"
                    puts "--------------------------"
                    puts "#{Team.all[0].name}"
                    puts "Location: #{Team.all[0].location}"
                    puts "Wins-Losses: #{Team.all[0].record}"
                    puts "Win %: #{Team.all[0].win * 100}"
                    puts "Playoff Seed: #{Team.all[0].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "2"
                    puts "--------------------------"
                    puts "#{Team.all[1].name}"
                    puts "Location: #{Team.all[1].location}"
                    puts "Wins-Losses: #{Team.all[1].record}"
                    puts "Win %: #{Team.all[1].win * 100}"
                    puts "Playoff Seed: #{Team.all[1].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "3"
                    puts "--------------------------"
                    puts "#{Team.all[2].name}"
                    puts "Location: #{Team.all[2].location}"
                    puts "Wins-Losses: #{Team.all[2].record}"
                    puts "Win %: #{Team.all[2].win * 100}"
                    puts "Playoff Seed: #{Team.all[2].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "4"
                    puts "--------------------------"
                    puts "#{Team.all[3].name}"
                    puts "Location: #{Team.all[3].location}"
                    puts "Wins-Losses: #{Team.all[3].record}"
                    puts "Win %: #{Team.all[3].win * 100}"
                    puts "Playoff Seed: #{Team.all[3].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "5"
                    puts "--------------------------"
                    puts "#{Team.all[4].name}"
                    puts "Location: #{Team.all[4].location}"
                    puts "Wins-Losses: #{Team.all[4].record}"
                    puts "Win %: #{Team.all[4].win * 100}"
                    puts "Playoff Seed: #{Team.all[4].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "6"
                    puts "--------------------------"
                    puts "#{Team.all[5].name}"
                    puts "Location: #{Team.all[5].location}"
                    puts "Wins-Losses: #{Team.all[5].record}"
                    puts "Win %: #{Team.all[5].win * 100}"
                    puts "Playoff Seed: #{Team.all[5].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "7"
                    puts "--------------------------"
                    puts "#{Team.all[6].name}"
                    puts "Location: #{Team.all[6].location}"
                    puts "Wins-Losses: #{Team.all[6].record}"
                    puts "Win %: #{Team.all[6].win * 100}"
                    puts "Playoff Seed: #{Team.all[6].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "8"
                    puts "--------------------------"
                    puts "#{Team.all[7].name}"
                    puts "Location: #{Team.all[7].location}"
                    puts "Wins-Losses: #{Team.all[7].record}"
                    puts "Win %: #{Team.all[7].win * 100}"
                    puts "Playoff Seed: #{Team.all[7].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "9"
                    puts "--------------------------"
                    puts "#{Team.all[8].name}"
                    puts "Location: #{Team.all[8].location}"
                    puts "Wins-Losses: #{Team.all[8].record}"
                    puts "Win %: #{Team.all[8].win * 100}"
                    puts "Playoff Seed: #{Team.all[8].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "10"
                    puts "--------------------------"
                    puts "#{Team.all[9].name}"
                    puts "Location: #{Team.all[9].location}"
                    puts "Wins-Losses: #{Team.all[9].record}"
                    puts "Win %: #{Team.all[9].win * 100}"
                    puts "Playoff Seed: #{Team.all[9].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "11"
                    puts "--------------------------"
                    puts "#{Team.all[10].name}"
                    puts "Location: #{Team.all[10].location}"
                    puts "Wins-Losses: #{Team.all[10].record}"
                    puts "Win %: #{Team.all[10].win * 100}"
                    puts "Playoff Seed: #{Team.all[10].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "12"
                    puts "--------------------------"
                    puts "#{Team.all[11].name}"
                    puts "Location: #{Team.all[11].location}"
                    puts "Wins-Losses: #{Team.all[11].record}"
                    puts "Win %: #{Team.all[11].win * 100}"
                    puts "Playoff Seed: #{Team.all[11].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "13"
                    puts "--------------------------"
                    puts "#{Team.all[12].name}"
                    puts "Location: #{Team.all[12].location}"
                    puts "Wins-Losses: #{Team.all[12].record}"
                    puts "Win %: #{Team.all[12].win * 100}"
                    puts "Playoff Seed: #{Team.all[12].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "14"
                    puts "--------------------------"
                    puts "#{Team.all[13].name}"
                    puts "Location: #{Team.all[13].location}"
                    puts "Wins-Losses: #{Team.all[13].record}"
                    puts "Win %: #{Team.all[13].win * 100}"
                    puts "Playoff Seed: #{Team.all[13].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "15"
                    puts "--------------------------"
                    puts "#{Team.all[14].name}"
                    puts "Location: #{Team.all[14].location}"
                    puts "Wins-Losses: #{Team.all[14].record}"
                    puts "Win %: #{Team.all[14].win * 100}"
                    puts "Playoff Seed: #{Team.all[14].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "16"
                    puts "--------------------------"
                    puts "#{Team.all[15].name}"
                    puts "Location: #{Team.all[15].location}"
                    puts "Wins-Losses: #{Team.all[15].record}"
                    puts "Win %: #{Team.all[15].win * 100}"
                    puts "Playoff Seed: #{Team.all[15].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "17"
                    puts "--------------------------"
                    puts "#{Team.all[16].name}"
                    puts "Location: #{Team.all[16].location}"
                    puts "Wins-Losses: #{Team..all[16].record}"
                    puts "Win %: #{Team..all[16].win * 100}"
                    puts "Playoff Seed: #{Team.all[16].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "18"
                    puts "--------------------------"
                    puts "#{Team.all[17].name}"
                    puts "Location: #{Team.all[17].location}"
                    puts "Wins-Losses: #{Team.all[17].record}"
                    puts "Win %: #{Team.all[17].win * 100}"
                    puts "Playoff Seed: #{Team.all[17].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "19"
                    puts "--------------------------"
                    puts "#{Team.all[18].name}"
                    puts "Location: #{Team.all[18].location}"
                    puts "Wins-Losses: #{Team.all[18].record}"
                    puts "Win %: #{Team.all[18].win * 100}"
                    puts "Playoff Seed: #{Team.all[18].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "20"
                    puts "--------------------------"
                    puts "#{Team.all[19].name}"
                    puts "Location: #{Team.all[19].location}"
                    puts "Wins-Losses: #{Team.all[19].record}"
                    puts "Win %: #{Team.all[19].win * 100}"
                    puts "Playoff Seed: #{Team.all[19].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "21"
                    puts "--------------------------"
                    puts "#{Team.all[20].name}"
                    puts "Location: #{Team.all[20].location}"
                    puts "Wins-Losses: #{Team.all[20].record}"
                    puts "Win %: #{Team.all[20].win * 100}"
                    puts "Playoff Seed: #{Team.all[20].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "22"
                    puts "--------------------------"
                    puts "#{Team.all[21].name}"
                    puts "Location: #{Team.all[21].location}"
                    puts "Wins-Losses: #{Team.all[21].record}"
                    puts "Win %: #{Team.all[21].win * 100}"
                    puts "Playoff Seed: #{Team.all[21].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "23"
                    puts "--------------------------"
                    puts "#{Team.all[22].name}"
                    puts "Location: #{Team.all[22].location}"
                    puts "Wins-Losses: #{Team.all[22].record}"
                    puts "Win %: #{Team.all[22].win * 100}"
                    puts "Playoff Seed: #{Team.all[22].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "24"
                    puts "--------------------------"
                    puts "#{Team.all[23].name}"
                    puts "Location: #{Team.all[23].location}"
                    puts "Wins-Losses: #{Team.all[23].record}"
                    puts "Win %: #{Team.all[23].win * 100}"
                    puts "Playoff Seed: #{Team.all[23].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "25"
                    puts "--------------------------"
                    puts "#{Team.all[24].name}"
                    puts "Location: #{Team.all[24].location}"
                    puts "Wins-Losses: #{Team.all[24].record}"
                    puts "Win %: #{Team.all[24].win * 100}"
                    puts "Playoff Seed: #{Team.all[24].seed.to_i}th"
                    puts "--------------------------"
                    list
                    puts "--------------------------"
                    puts "Please select another team or type 'exit' to leave."
                when "list"
                    list
                end
            end
    end

    def welcome
        puts "Welcome to the NBA. Please select a team for more information."
    end

    def list
        self.display_team_list
    end

    def display_team_list
        Team.all.each.with_index(1)do |team, i|
            puts "#{i}. #{team.name}"
        end
    end
  
end